export const AUTHENTICATED = 'AUTHENTICATED'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_TOKEN = 'FETCH_TOKEN'
export const LOGOUT = 'LOGOUT'
export const SNACKBAR = 'SNACKBAR'
export const REGISTER = 'REGISTER'
